RandomDraw/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import urls as accounts_url
from main import urls as main_url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(accounts_url)),
    path('main/', include(main_url)),
]

main/urls.py
from django.urls import path
from . import views

from django.conf.urls.static import static
from django.conf import settings
from rest_framework.routers import DefaultRouter
from .views import CapsuleViewSet

app_name = 'main'


urlpatterns = [
    path('write_capsule/', views.write_capsule, name='write_capsule'),
    path('show_capsule/', views.show_capsule, name='show_capsule'),
    path('show_all_picked_capsule/', views.show_all_picked_capsule, name='show_all_picked_capsule'),
    path('show_all_my_capsule/', views.show_all_my_capsule, name='show_all_my_capsule'),
    path('modal/', views.modal, name='modal')
]

main/models.py
from django.db import models
# from .models import User

class Capsule(models.Model):
    email = models.EmailField()
    content = models.TextField(verbose_name='내용')
    picture = models.TextField(verbose_name='사진')
#     image = models.ImageField(default='media/default_image.jpeg', null=True)

    
    DESTINATION_CHOICES = [
        ("unknown", "익명"),
        ("tome", "나")
    ]

    OPEN_DATE_CHOICES = [
        ("minute", "1분 후"),
        ("month", "1개월 후"),
        ("3month", "3개월 후"),
        ("6month", "6개월 후"),
        ("1year", "1년 후")
    ]
    
    destination = models.CharField(max_length=7, choices=DESTINATION_CHOICES)
    write_date = models.DateTimeField(auto_now=True)
    open_date = models.CharField(max_length=6, choices=OPEN_DATE_CHOICES)

class picked_capsule(models.Model):
    account_info_email = models.CharField(max_length=100)
    picked_capsule_id = models.AutoField(primary_key=True)
    info_write_date = models.DateTimeField()
    info_open_date = models.DateTimeField()
    info_content = models.TextField()
    info_picture = models.TextField()

main/forms.py
from django import forms
from .models import Capsule, picked_capsule

class CapsuleCreateForm(forms.ModelForm):
    class Meta:
        model = Capsule
        fields = ['content', 'picture', 'destination', 'open_date']

class pickedcapsuleForm(forms.ModelForm):
    class Meta:
        model = picked_capsule
        field = ['account_info_email',
    'info_write_date',
    'info_open_date',
    'info_content',
    'info_picture']

main/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.contrib.auth.decorators import login_required
from accounts.models import Accounts
from .models import Capsule, picked_capsule
# from .forms import CapsuleCreateForm
import json, random
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse
# from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from .serializers import CapsuleSerializer

# @permission_classes([IsAuthenticated])
@csrf_exempt
def write_capsule(request):
    requestdata = json.loads(request.body.decode('utf-8'))
    requestdata = json.loads(request.body)
    print(requestdata)

    contentd = requestdata['content']
    destionationd =  requestdata['destination']
    open_dated = requestdata['open_date']

    cap = Capsule(content = contentd, destination = destionationd, open_date = open_dated, picture = "fskjbkj", email = 'seo4306@kookmin.ac.kr', )
    cap.save()

    return JsonResponse({'result' : "success"}, json_dumps_params={'ensure_ascii': False}, content_type = 'application/json; charest=utf-8')
    
# from rest_framework import viewsets
# from rest_framework.views import APIView


# class CapsuleViewSet(APIView):
#     queryset = Capsule.objects.all() 
#     serializer_class = CapsuleSerializer

#     def get(self, request, **kwargs): 
#         queryset = Capsule.objects.all()
#         queryset_serializer = CapsuleSerializer(queryset, many=True)
#         return Response(queryset_serializer.data)

#     def post(self, request):
#         user_email = "appleid5@naver.com"

#         try:
#             user = Accounts.objects.get(email=user_email)
#         except Accounts.DoesNotExist:
#             return Response("User not found", status=404)
        
#         serializer = CapsuleSerializer(data=request.data, context={'user_email': user_email})

#         if serializer.is_valid():
#             serializer.save() 
#             return Response(serializer.data)
        
#         return Response(serializer.errors, status=400)


#     def perform_create(self, serializer):
#         # Serializer의 save 메서드를 오버라이드하여 user_email을 저장
#         serializer.save(email=self.request.data.get('email'))

#     def list(self, request):
#         serializer = CapsuleSerializer(self.queryset, many=True)
#         return Response(serializer.data)
    
    # if request.method == 'POST':
    #     form = CapsuleCreateForm(request.POST, request.FILES)
    #     if form.is_valid():
    #         new_capsule = form.save(commit=False)
    #         new_capsule.user = user
    #         new_capsule.email = user_email
    #         new_capsule.save()
    #         return JsonResponse({'success': True})
    # else:
    #     form = CapsuleCreateForm()
    # return render(request, 'write_capsule.html', {'form': form})

@csrf_exempt
def show_capsule(request): # 사용자 제외 랜덤
    user_email = 'seo4306@kookmin.ac.kr'
    # user = Accounts.objects.get(email=user_email)

    # capsules_exclude_user = Accounts.objects.exclude(user=user)
    # random_capsule = random.choice(capsules_exclude_user)
# def show_capsule(request): 
#     if request.method == 'GET':
#         # user_email = request.session['email']
#         # user = Accounts.objects.get(email=user_email)
#         user_email = "app@naver.com"
#         random_capsule = Capsule.objects.exclude(email=user_email)
#         print(random_capsule)
#         return JsonResponse({'id': random_capsule.id, 'content': random_capsule.content}, json_dumps_params={'ensure_ascii': False}, content_type='application/json; charset=utf-8')

    Capsules = get_object_or_404(Capsule, id = 12)
    return JsonResponse({'content':Capsules.content, 'date' : Capsules.write_date}, json_dumps_params={'ensure_ascii':False}, content_type = 'application/json; charest=utf-8')
@csrf_exempt
def show_all_picked_capsule(request):
    # user_email = request.session['email']
    user_email = 'seo4306@kookmin.ac.kr'
    try:
        Capsules = get_list_or_404(picked_capsule, account_info_email = user_email)
        ac = get_object_or_404(Accounts, email = user_email)
        name = ac.name
        jsonarray = []
        for capsule in Capsules:
            jsonarray.append({'writedate' : capsule.info_write_date})

        return JsonResponse({'name' : name, 'array' : jsonarray}, json_dumps_params={'ensure_ascii': False}, content_type = 'application/json; charest=utf-8')
        
    except:
        return JsonResponse({'result' : "fail"}, json_dumps_params={'ensure_ascii': False}, content_type = 'application/json; charest=utf-8')
    
@csrf_exempt
def show_all_my_capsule(request):
    # user_email = request.session['email']
    user_email = 'seo4306@kookmin.ac.kr'
    try:
        Capsules = get_list_or_404(Capsule, email = user_email)
        ac = get_object_or_404(Accounts, email = user_email)
        name = ac.name
        jsonarray = []
        for i in range(len(Capsules)):
            if i < 3:
                jsonarray.append({'writedate' : Capsules[i].write_date, 'lock' : True})
            else: 
                jsonarray.append({'writedate' : Capsules[i].write_date, 'lock' : False})
        return JsonResponse({'name' : name, 'array' : jsonarray}, json_dumps_params={'ensure_ascii': False}, content_type = 'application/json; charest=utf-8')
        
    except:
        return JsonResponse({'result' : "fail"}, json_dumps_params={'ensure_ascii': False}, content_type = 'application/json; charest=utf-8')
@csrf_exempt  
def modal(request):
    # requestdata = json.loads(request.body.decode('utf-8'))
    # requestdata = json.loads(request.body)
    # print(requestdata)


    # wt = requestdata['index']
    idi = 11
    cap = get_object_or_404(Capsule, id = idi)

    wd = cap.write_date
    ct = cap.content

    return JsonResponse({'time' : wd, 'content' : ct}, json_dumps_params={'ensure_ascii': False}, content_type = 'application/json; charest=utf-8')
        

main/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>추억뽑기</title>
    <style>
        @font-face { font-family: 'yangjin'; src: url('https://cdn.jsdelivr.net/gh/supernovice-lab/font@0.9/yangjin.woff') format('woff'); font-weight: 100; font-style: normal; }
        /* 회전 애니메이션*/
        @keyframes rotate {
            0% { transform: rotate(0deg); }
            25% { transform: rotate(90deg); }
            50% { transform: rotate(180deg); }
            75% { transform: rotate(270deg); }
            100% { transform: rotate(360deg); }
        }
        @keyframes shaker{
            0% { transform: rotate(10deg); }
            100% { transform: rotate(-10deg); }
        }
        
        /* rotate 클래스를 적용하면 회전 애니메이션이 적용됩니다. */
        .rotate {
            animation: rotate 3s linear infinite;
        }
        .shaker {
            animation: shaker 0.5s ease-in-out infinite alternate;
        }
    </style>
</head>
<body style="background: #D6C4A3; align-items: center; justify-self: center;">
    <div>
        <div class="Rectangle16" style="width: 257px; height: 168px; left: 591px; top: 518px; position: absolute; background: #C61511; border-radius: 22px; border: 5px black solid"></div>
        <div class="Rectangle21" style="left: 740px; top: 548px; position: absolute;">
        <image src="case.png" width="90"></div>
            <button class="Rectangle32" style="left: 632px; top: 550px; position: absolute; background: none; border: none; padding: 0; cursor: pointer; z-index: 2" onclick="sharot()">
                <img src="putcoin.png" width="90" alt="Put Coin">
            </button>
        <div style="width: 281px; height: 298px; left: 579px; top: 185px; position: absolute;">
            <image src="cover.png" class="cover" width="290"></div>
        <div class="Ellipse11" style="left: 580px; top: 420px; position: absolute;">
            <image src="Group 8.png" id="cap1" width="120"></div>
        <div class="Ellipse19" style="left: 750px; top: 425px; position: absolute;">
            <image src="Group 9.png" id="cap2" width="120"></div>
        <div class="Ellipse17" style="left: 670px; top: 400px; position: absolute;">
            <image src="Group 10.png" id="cap3" width="110"></div>
        <div class="Ellipse15" style=" left: 730px; top: 340px; position: absolute;">
            <image src="Group 11.png" id="cap4" width="120"></div>
        <div class="Ellipse21" style="left: 615px; top: 340px; position: absolute;">
            <image src="Group 12.png" id="cap5" width="90"></div>
        <div class="Ellipse13" style="left: 673px; top: 272px; position: absolute;">
            <image src="Group 13.png" id="cap6" width="120"></div>
        <div class="Rectangle45" style="width: 720px; height: 630px; left: 357px; top: 89px; position: absolute; background: rgba(217, 217, 217, 0); border-radius: 50px; border: 10px #734B45 solid"></div>
        <div class="Rectangle46" style="width: 683px; height: 600px; left: 377px; top: 108px; position: absolute; background: rgba(217, 217, 217, 0); border-radius: 50px; border: 5px #734B45 solid"></div>
        <div class="Rectangle47" style="width: 260px; height: 80px; left: 589px; top: 60px; position: absolute; background: #D6C4A3; border: 7px #734B45 solid"></div>
        <div style="width: 200px; height: 63px; left: 640px; top: 79px; position: absolute; color: #734B45; font-size: 45px; font-family: 'yangjin'; font-weight: 600; word-wrap: break-word">추억 뽑기</div>
        <div class="Ellipse22" style="width: 73px; height: 70px; left: 1290px; top: 25px; position: absolute; background: white; border-radius: 9999px"></div>
        <div style="width: 54px; height: 34px; left: 1230px; top: 46px; position: absolute; color: #F5F5F5; font-size: 25px; font-family: 'yangjin'; font-weight: 600; word-wrap: break-word">별명</div>
        <div style="left: 1170px; top: 110px; position: absolute; color: black; font-size: 22px; font-family: 'yangjin'; font-weight: 600; word-wrap: break-word">
        <image src="coin.png" width="100"></div>
        <div style="width: 146px; height: 36px; left: 1280px; top: 130px; position: absolute; color: black; font-size: 32px; font-family: 'yangjin'; font-weight: 600; word-wrap: break-word" id="amount">1000원</div>
        <div class="Frame1" style="width: 100px; height: 100px; left: 632px; top: 189px; position: absolute"></div>
    </div>

    <script>
        let amount=1000;
        function sharot() {
            // 회전할 이미지들
            if (amount < 500) {
        alert('동전이 부족해요. 편지를 쓰러갈까요?');
        return; // 함수 종료
            }
            else {
                amount-=500;
                updateAmount(amount);

            }
            const shImages = document.getElementsByClassName('cover');
            const capImages = [
                document.getElementById('cap1'),
                document.getElementById('cap2'),
                document.getElementById('cap3'),
                document.getElementById('cap4'),
                document.getElementById('cap5'),
                document.getElementById('cap6')
            ];

            Array.from(shImages).forEach((shImage) => {
            shImage.classList.add('shaker'); //shaker 클래스를 추가하여 애니메이션 적용
        });
        // 각 이미지에 대해 효과 적용
        capImages.forEach((cap, index) => {
                cap.classList.add('rotate'); // rotate 클래스를 추가하여 회전 애니메이션 적용
            });
            

        // 3초 후 rotate 클래스 제거
        setTimeout(() => {
            Array.from(shImages).forEach((shImage) => {
                shImage.classList.remove('shaker');// shaker 클래스를 제거하여 애니메이션 중지
                });
            }, 3000);

            setTimeout(() => {
                capImages.forEach((cap) => {
                    cap.classList.remove('rotate'); // rotate 클래스를 제거하여 애니메이션 중지
                    showcapsule();
                });
            }, 3000);
        }
        function showcapsule() {
    // 캔버스 생성
    const canvas = document.createElement('canvas');
    canvas.width = 900;
    canvas.height = 900;
    canvas.style.position = 'absolute';
    canvas.style.zIndex = '3';
    document.body.appendChild(canvas);

    const ctx = canvas.getContext('2d');

    // 이미지 가져오기
    const image = new Image();
    image.src = 'capsules.png'; // 이미지 경로 설정

    // 초기값 설정
    let imageSize = 50;
    let x = 740;
    let y = 548;
    let opacity = 0;    

    // 애니메이션 함수
    function animate() {
        // 캔버스 클리어
        ctx.clearRect(0, 0, canvas.width, canvas.height);

        
        // 이미지 그리기
        ctx.globalAlpha = opacity;
        ctx.drawImage(image, x, y, imageSize, imageSize);
        ctx.globalAlpha = 1; // 원래 상태로 돌려놓기

        // 이미지 크기 증가
        imageSize += 2;

        // 이미지 이동
        y -= 2.5;
        x-=1.4;

        // 투명도 증가
        opacity += 0.01;

        // 특정 위치에 도달하면 애니메이션 중단
        if (imageSize>= 300) { 
            return;
        }
        canvas.addEventListener('click', function () {
                // 이미지 클릭 시 숨기고 함수 종료
                canvas.style.display = 'none';
            });
        // 애니메이션 프레임 요청
        requestAnimationFrame(animate);
    }

    // 이미지 로딩 후 애니메이션 시작
    image.onload = function () {
        animate();
    };
}

function updateAmount(newAmount) {
        const amountElement = document.getElementById('amount');
        if (amountElement) {
            amountElement.textContent = newAmount + '원';
        }
    }

    </script>
</body>
</html>

main/templates/my_page.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>내 추억 저장소</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="../my_page.css">
  </head>

  <body>
  <h1>내 추억 저장소</h1>
  <div id="user-nickname">(별명)
    <script>
      document.getElementById('user-nickname').textContent = username;
    </script>
  </div>
  

  <div class="tabmenu out-tabmenu">
    <ul>
      <li id="tab1" class="btnCon"> 
    
        <input type="radio" checked name="tabmenu" id="tabmenu1">
        <label for="tabmenu1">나의 추억</label>
        <div class="tabCon" >
            <div class="default-message" id="test1">나의 추억을 만들고 일정 시간 후에 확인해보세요.</div>
            <button type="button" id="btn">버튼</button>
            </div>
      </li>
      <li id="tab2" class="btnCon">
        <input type="radio" name="tabmenu" id="tabmenu2">
        <label for="tabmenu2">뽑은 추억</label>
        <div class="tabCon" >
            <div class="default-message" id="test2">다른 사용자의 추억을 뽑아보세요.</div>
            <button type="button" id="btn2">버튼</button>
        </div>
      </li>
    </ul>
  </div>


  <div class="modal fade" id="timeCapsuleModalToggle" aria-hidden="true" aria-labelledby="timeCapsuleModalToggleLabel" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="created-date">(20XX.XX.XX X요일)</h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="capsule-photo-container"><img class="capsule-photo" src="." alt="추억 사진" /></div>
          
          <button class="arrow-button" data-bs-target="#timeCapsuleModalToggle2" data-bs-toggle="modal">
            <i class="arrow right"></i></button>
        </div>
      </div>
    </div>
  </div>

  
  <div class="modal fade" id="timeCapsuleModalToggle2" aria-hidden="true" aria-labelledby="timeCapsuleModalToggleLabel2" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="created-date">(20XX.XX.XX X요일)</h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <button class="arrow-button" data-bs-target="#timeCapsuleModalToggle" data-bs-toggle="modal">
            <i class="arrow left"></i></button>
          <div class="capsule-content">추억 내용 추억 내용 추억 내용 추억 내용 추억 내용 추억 내용 추억 내용 추억 내용 추억 내용 추억 내용 추억 내용 추억 내용</div>
        </div>
      </div>
    </div>
  </div>


  <script>
    let i = 0;

    function createCapsule() {  // 락 걸린 캡슐 만들기
        const tabCon = document.querySelector('.tabCon');
        const capsuleImages = ["1-locked.png", "2-locked.png"];
        const chosenImage = capsuleImages[i];

        const capsuleContainerButton = document.createElement('button');
        capsuleContainerButton.className = 'transparent-button';
        capsuleContainerButton.setAttribute('data-bs-target', '#timeCapsuleModalToggle');
        capsuleContainerButton.setAttribute('data-bs-toggle','modal');
        capsuleContainerButton.style.display = 'inline-block';
        capsuleContainerButton.style.flexDirection = 'column';
        capsuleContainerButton.style.textAlign = 'center';
        capsuleContainerButton.style.width = '100px';
        capsuleContainerButton.style.marginRight = '15px';
        capsuleContainerButton.style.marginBottom = '15px';
        capsuleContainerButton.style.cursor = 'pointer';

        

        const capsule = document.createElement('img');
        capsule.src = `../../capsule${chosenImage}`;
        capsule.style.width = '100px';
        capsule.style.marginBottom = '10px';
        
        const createdDate = document.createTextNode('20XX.XX.XX');  // 작성 날짜 받아오기
        
        capsuleContainerButton.appendChild(capsule);
        capsuleContainerButton.appendChild(createdDate);
        tabCon.appendChild(capsuleContainerButton);

        i = (i + 1) % 2;
        if (tabCon.querySelector('img')) {
            tabCon.querySelector('.default-message').remove();
        }
    }
    // 사용자가 작성 페이지에서 추억을 작성하면(버튼을 클릭하면) 캡슐 생성
    document.getElementById('btn').addEventListener('click', createCapsule);
    

  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

main/templates/show_capsule.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Show Capsule</title>
</head>
<body>
    <h1>Capsule Details</h1>
    <p>Capsule ID: {{ capsule.id }}</p>
    <p>{{ capsule.content }} </p>
</body>
</html>

main/templates/write_capsule.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <form id="capsuleCreateForm" action="{% url 'main:write_capsule' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="저장">
    </form>
</body>
</html>